services:
    nginx:
        image: nginx:debian
        build: ./requirements/nginx/
        container_name: nginx
        ports:
            - "443:443"
        volumes:
            - wordpress_data:/var/www/wordpress/
        restart: on-failure
        networks:
            - inception_network
        depends_on:
            - wordpress
    
    # mariadb:
    #     image: mariadb:10.5
    #     build: ./requirements/mariadb
    #     container_name: mariadb
    #     expose:
    #         - 3306
    #     restart: always
    #     env_file: .env
    #     #healthcheck

    wordpress:
        image: wordpress:6.7
        ports:
            - "9000:9000"
        build: ./requirements/wordpress/
        container_name: wordpress
        volumes:
            - wordpress_data:/var/www/html/
        working_dir: /var/www/html/
        env_file: .env
        restart: on-failure
        networks:
            - inception_network
        #depends_on:
        #    - mariadb

volumes:
    wordpress_data:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/Users/gcatarin/data/wordpress'

networks:
    inception_network:
        driver: bridge