services:
    nginx:
        build: ./requirements/nginx/
        container_name: nginx
        ports:
            - "80:80"
        command: printf "\033[0;36m" || echo "BUILDING NGINX" || printf "'\033[0m'"
        restart: always
    
    mariadb:
        image: mariadb:10.5
        build: ./requirements/mariadb
        container_name: mariadb
        expose:
            - 3306
        restart: always
        env_file: 
            - .env
        #healthcheck

    #wordpress:
    #    build: ./srcs/wordpress/
    #    container_name: wp-php
    #    restart: always

    #    command: printf "\033[0;36m" || echo "BUILDING WORDPRESS" || printf "'\033[0m'"